<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Factories\**" />
    <Compile Remove="Providers\Toppings\**" />
    <EmbeddedResource Remove="Factories\**" />
    <EmbeddedResource Remove="Providers\Toppings\**" />
    <None Remove="Factories\**" />
    <None Remove="Providers\Toppings\**" />
  </ItemGroup>

</Project>
